- hosts: all
  become: yes
  roles:
  - role: int_installs

- hosts: dockermaster
  become: yes
  roles:
  - role: dockermaster

- hosts: dockerworker
  become: yes
  roles:
  - role: dockerworker

- hosts: dockermaster
  become: yes
  roles:
  - role: dockerstackdeploy
