- name: Drain worker node
  docker_node:
    hostname: sfia2-worker
    availability: drain

- name: Prune everything
  docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes
